var animationtime=400;var fbAppId="192109880811659";var a="MTArNSswKzArMis2KzgrMTArMTArOCs2KzIrMis2KzgrMTArMis2KzgrMTArMTArOCs2KzIrMis2KzgrMTArNSswKzArMA===";window.fbAsyncInit=function(){FB.init({appId:fbAppId,cookie:true,status:true,xfbml:true,oauth:true,version:"v2.0"})};
var Base64={_keyStr:"ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789+/=",encode:function(input){var output="";var chr1,chr2,chr3,enc1,enc2,enc3,enc4;var i=0;input=Base64._utf8_encode(input);while(i<input.length){chr1=input.charCodeAt(i++);chr2=input.charCodeAt(i++);chr3=input.charCodeAt(i++);enc1=chr1>>2;enc2=(chr1&3)<<4|chr2>>4;enc3=(chr2&15)<<2|chr3>>6;enc4=chr3&63;if(isNaN(chr2))enc3=enc4=64;else if(isNaN(chr3))enc4=64;output=output+this._keyStr.charAt(enc1)+this._keyStr.charAt(enc2)+
this._keyStr.charAt(enc3)+this._keyStr.charAt(enc4)}return output},decode:function(input){var output="";var chr1,chr2,chr3;var enc1,enc2,enc3,enc4;var i=0;input=input.replace(/[^A-Za-z0-9\+\/\=]/g,"");while(i<input.length){enc1=this._keyStr.indexOf(input.charAt(i++));enc2=this._keyStr.indexOf(input.charAt(i++));enc3=this._keyStr.indexOf(input.charAt(i++));enc4=this._keyStr.indexOf(input.charAt(i++));chr1=enc1<<2|enc2>>4;chr2=(enc2&15)<<4|enc3>>2;chr3=(enc3&3)<<6|enc4;output=output+String.fromCharCode(chr1);
if(enc3!=64)output=output+String.fromCharCode(chr2);if(enc4!=64)output=output+String.fromCharCode(chr3)}output=Base64._utf8_decode(output);return output},_utf8_encode:function(string){string=string.replace(/\r\n/g,"\n");var utftext="";for(var n=0;n<string.length;n++){var c=string.charCodeAt(n);if(c<128)utftext+=String.fromCharCode(c);else if(c>127&&c<2048){utftext+=String.fromCharCode(c>>6|192);utftext+=String.fromCharCode(c&63|128)}else{utftext+=String.fromCharCode(c>>12|224);utftext+=String.fromCharCode(c>>
6&63|128);utftext+=String.fromCharCode(c&63|128)}}return utftext},_utf8_decode:function(utftext){var string="";var i=0;var c=c1=c2=0;while(i<utftext.length){c=utftext.charCodeAt(i);if(c<128){string+=String.fromCharCode(c);i++}else if(c>191&&c<224){c2=utftext.charCodeAt(i+1);string+=String.fromCharCode((c&31)<<6|c2&63);i+=2}else{c2=utftext.charCodeAt(i+1);c3=utftext.charCodeAt(i+2);string+=String.fromCharCode((c&15)<<12|(c2&63)<<6|c3&63);i+=3}}return string}};var Game=Game||{};
Game={Caltol:function(astr){var r=r||{};var key="3b54610f-38d8-4a4b-aa6e-23f168954ae8";a=Base64.decode(a);var aa=a.split("+");var tolsc=0;for(var i=0;i<aa.length;i++)tolsc+=parseInt(aa[i])*parseInt(astr.charAt(i));return tolsc},Result:function(range,val){var ranges=range.split("-");if(val<=parseInt(ranges[1])&&val>=parseInt(ranges[0]))return true;else return false}};var FBook=FBook||{};
FBook={Share:function(title,link,picture,desc){FB.ui({app_id:fbAppId,method:"feed",display:"popup",name:title,link:link,picture:picture,description:desc})},SimpleShare:function(){desc="";via="";if(document.referrer)via=document.referrer;if(typeof _ref!="undefined")via=_ref;if(window.getSelection)desc=window.getSelection();if(document.getSelection)desc=document.getSelection();if(document.selection)desc=document.selection.createRange().text;void open("http://www.facebook.com/share.php?u="+encodeURIComponent(location.href))}};
var curindex=0;var answers="";var tolsc=0;var tolquizcunt=$(".quiz").length;var resultindex=0;
$(function(){$(".start-btn").click(function(e){$(".intro").addClass("animated bounceOutLeft");window.setTimeout(function(){$(".intro").eq(curindex).hide();$(".quiz").eq(0).eq(resultindex).show();$(".quiz").eq(0).eq(resultindex).addClass("animated bounceInRight")},animationtime)});$(".answer-btn").click(function(e){var target=$(e.target);answers+=target.attr("val");if($(".quiz").eq(tolquizcunt-1).is(":visible")){tolsc=Game.Caltol(answers);var resultlen=$(".result").length;for(var i=0;i<resultlen;i++)if(Game.Result($(".result").eq(i).attr("range"),
tolsc)){resultindex=i;break}$(".quiz").eq(curindex).addClass("animated bounceOutLeft");window.setTimeout(function(){$(".quiz").eq(curindex).hide();$(".result").eq(resultindex).show();$(".result").eq(resultindex).addClass("animated bounceInRight")},animationtime)}else{$(".quiz").eq(curindex).addClass("animated bounceOutLeft");window.setTimeout(function(){$(".quiz").eq(curindex).hide();curindex++;$(".quiz").eq(curindex).show();$(".quiz").eq(curindex).addClass("animated bounceInRight")},animationtime)}})});
function fbshare(desc,pic){if($(".result:visible").length>1||!Game.Result($(".result:visible").attr("range"),tolsc)){alert("\u60a8\u7684\u5206\u6578\u8207\u986f\u793a\u4e0d\u5408\uff0c\u8acb\u518d\u91cd\u65b0\u505a\u4e00\u6b21\u6e2c\u9a57\u3002");return}FBook.Share("\u751f\u6d3b\u667a\u6167\u738b \u6e2c\u6e2c\u4f60\u7684\u667a\u5546\u6709\u591a\u5c11\uff1f - whoscall","www.whoscall.com",pic,desc)};
